# Environment Decision
[env:esp32s3]

#Haredware Config
#Downalods the ESP32 Compiler chain
#Specific board model - set pin definitions, memory size
# Using Aruduino framework 
platform: espressif32
board: esp32-s3-devkitc-1
framework = arduino

#Monitor Baurd Rate(Communication Speed)  115200 Bits/second
#Upload Speed - Higher: Faster Downloads, ESP32 - SUupports upto 921600
monitor_speed = 115200
UPLOAD_SPEED = 921600

#Libraries: Auto-download Libraries When You Compile 
lib_deps=
    bodmer/TFT_eSPI@^2.5.43 #Controls Colors TFT Diplays
    bblanchon/ArduinoJson@^7.2.0 #Parse JSON from Groq API key
    

#Complier Flags: Special Instructions for the compiler
build_Flags=
    -DDCORE_DEBUG_LEVEL=0 #No Debug Messages makes code smaller and faser 0=none, 1=errors, 2=warnings, 3=Info, 4=Debug, 5=verbose
    -DBOAD_HAD_PSRAM #Tells complier this board has estra PSRAM memory Enables PSRAM usage in libraries
    
